/* Creating custom commands*/

const { program } = require('commander');

program
  .option('--first')
  .option('-s, --separator <char>');

program.parse();

const options = program.opts();
const limit = options.first ? 1 : undefined;
console.log(program.args[0].split(options.separator, limit));


-----------------------------------------------------------------------

const {program} = require('commander');

const newProgram = new program();

newProgram
	.name('string-util')
	.description('CLI to some JavaScript string utilities');

newProgram.command('split')
  .description('Split a string into substrings and display as an array')
  .argument('<string>', 'string to split')
  .option('--first', 'display just the first substring')
  .option('-s, --separator <char>', 'separator character', ',')
  .action((str, options) => {
    const limit = options.first ? 1 : undefined;
    console.log(str.split(options.separator, limit));
  });

/*
 * creates a new command 'Split' wiht given description 
 * @param a string  
 * @option --first which will show first substring.
 * @option -s with a charecter to split original string from (default ',')
 * @option --help it is generated by default.
 *
 * str.split {function} splits the string at each position of seperator.
 */

//RADHE RADHE RAM RAM
